### ISSUE TITLE
Games, that rely on Windows registry to locate the game data directory, don't work

### ISSUE THREAD

**Issue by Mastergatto** [popsUlfr/Proton#6]
One example is Fallout 3 Goty, in HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Bethesda Softworks\fallout3, with the "installed path" key:
```
reg: The system was unable to find the specified registry key or value
Z:\path\to\SteamLibrary\steamapps\common\Fallout 3 goty\
```
That one being shown in regedit as one line with a special character like /n on some text editor in between to mark a new line. 
When being launched, Fallout 3 complains that can't find the executable or the installer.

I'm aware of at least another game (SPORE) that has the same issue. I don't know that's the matter, but with vanilla Proton those games work without issues.

**Comment by popsUlfr** [comment]
I will test this next time I get some time in Fallout 3.

But I don't see how the changes compared to the official proton would have any effect on this, this sounds more like a wine prefix that got corrupted or something to that effect.

Can you replicate this with a fresh reinstallation of Fallout 3 ? (also removing the wine prefix in compatdata)

**Comment by Mastergatto** [comment]
I have just done that (including erasing the prefix), it yields the same result.

**Comment by popsUlfr** [comment]
I can confirm. Maybe it's related to the fact that the installscript for the game is not launched with a custom proton ?

![screenshot_20181230_150942](https://user-images.githubusercontent.com/1030423/50547967-06ed4300-0c45-11e9-959a-82f111d43a6d.png)

Ok I think it's because steam parses the output the gallium registry stuff will spew out a harmless error because it couldn't find the key to delete : 
https://github.com/popsUlfr/Proton/blob/7ba036ae9ff4f768c5b6bc1a8a4ebcbf52b4e7bc/proton#L431-L439

@Mastergatto Could you comment out that section in the `proton` file ?

- Switch to the official proton 3.16-6 launch the game once and confirm you get into the game.
- Switch to the Gallium Nine proton and try launching the game now.

So that works for me, might be the same problem for the other issues about installing the dependencies as well like #7 

@Mastergatto Can you confirm that https://github.com/popsUlfr/Proton/commit/ecc05f16def0f3d4524139ea03e22e1809917e05 fixes the issue ? It works on my end.

**Comment by Mastergatto** [comment]
Fallout 3 and SPORE now work correctly with those changes (ecc05f1), good job! :+1:

EDIT: Wait, I try to comment out that section to see what happens now, brb
EDIT2: It seems to work without that section
